[fix] extra import of pprint in devtools/make_help.py can cause error
The error is:
Traceback (most recent call last):
  File "devtools/make_help.py", line 706, in <module>
    main(sys.argv)
  File "devtools/make_help.py", line 577, in main
    d = pprint.pformat(topic_lookup)
UnboundLocalError: local variable 'pprint' referenced before assignment